* Read the paper and understand theory behind PlaNet.
** Open questions:
*** Does a belief state is inferred from start of the sequence or from start of the chunk?
** Answered questions:
*** What does open/closed loop means for image statistics?
    The closed loop prior is a one-step prediction and the closed loop posterior is a 0-step reconstruction. Open loop means predicting forward for multiple steps without receiving intermediate image inputs.
* Train PlaNet in the small Sokoban environment.
  It didn't train. It doesn't capture Sokoban dynamics, everything gets blurred, multiple agents appear, etc.
** Understand PlaNet summaries to know if it trains.
*** What is entropy and should it grow or rather shrink?
** What might go wrong with PlaNet for Sokoban:
*** `argmax` policy may introduce high variance or impair exploration, /should you use “softer” stochastic policy?/
*** In Sokoban an initial state $$ s_0 $$ _is not_ fixed! A Sokoban board is randomly generated at each episode. PlaNet was able to solve a multitask environment, /but isn't that too much for it?/
